spring.application.name=notification-service
server.port=8083

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:todo}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:todo}
